[package]
name = "cli-ai-rpg"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
rand = "0.9.0"
strum = "0.27.0"
strum_macros = "0.27.0"
serde = { version = "1.0.217", features = ["derive"]}
serde_json = "1.0.138"
petgraph = "0.7.1"
